// web/src/pages/Profile.vue
<template>
  <div class="min-h-screen bg-gray-50 p-4 sm:p-8">
    <div v-if="!currentUser" class="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <p class="text-center text-xl text-gray-700 bg-white p-8 rounded-lg shadow-lg">
        Please log in to view your profile.
      </p>
    </div>

    <div v-else class="max-w-5xl mx-auto">
      <h1 class="text-4xl font-extrabold text-gray-900 mb-8 border-b pb-4">
        {{ editing ? 'Edit Your Profile' : 'My Profile' }}
      </h1>

      <div class="bg-white rounded-xl shadow-2xl border border-gray-100 p-6 sm:p-8 space-y-8">
        <div class="flex flex-col sm:flex-row items-center sm:items-start space-y-4 sm:space-y-0 sm:space-x-8 pb-6 border-b border-gray-100">
          <div class="relative">
            <img
              :src="currentUser.profile_picture || 'placeholder.jpg'"
              alt="Profile"
              class="w-32 h-32 rounded-full object-cover border-4 border-white shadow-lg"
            />
            <span :class="['absolute bottom-0 right-0 h-4 w-4 rounded-full ring-2 ring-white', currentUser.is_active ? 'bg-green-400' : 'bg-red-400']" :title="currentUser.is_active ? 'Active' : 'Inactive'"></span>
          </div>

          <div class="text-center sm:text-left">
            <h2 class="text-3xl font-bold text-blue-800">{{ currentUser.first_name || currentUser.username }} {{ currentUser.last_name }}</h2>
            <p class="text-lg text-gray-600 italic">{{ currentUser.role === 'instructor' ? 'Instructor' : 'Student' }}</p>
            <p class="text-gray-500 text-sm mt-1">Joined: {{ formatDate(currentUser.date_joined) }}</p>
            <p v-if="currentUser.last_activity" class="text-gray-500 text-sm">Last Activity: {{ formatDateTime(currentUser.last_activity) }}</p>
            
            <button 
              @click="setEditing(!editing)" 
              :class="['mt-3 px-4 py-2 rounded-lg font-semibold transition', editing ? 'bg-gray-300 text-gray-800 hover:bg-gray-400' : 'bg-blue-600 text-white hover:bg-blue-700 shadow-md']"
            >
              {{ editing ? 'Cancel Edit' : 'Edit Profile' }}
            </button>
          </div>
        </div>

        <form @submit.prevent="handleEditSubmit" class="space-y-6">
          <section>
            <h3 class="text-xl font-bold text-gray-800 mb-4 border-b pb-2">Personal Information</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div v-for="field in editableFields" :key="field.key">
                <div v-if="editing">
                  <label :for="field.key" class="form-label">{{ field.label }}</label>
                  
                  <input
                    v-if="['text', 'date', 'url', 'email', 'number'].includes(field.type)"
                    :type="field.type"
                    :id="field.key"
                    :name="field.key"
                    :value="form[field.key]"
                    @input="handleEditChange"
                    class="form-input"
                  />
                  <textarea
                    v-else-if="field.type === 'textarea'"
                    :id="field.key"
                    :name="field.key"
                    :value="form[field.key]"
                    @input="handleEditChange"
                    class="form-input resize-y h-24"
                  ></textarea>
                  <select
                    v-else-if="field.type === 'select' && field.options"
                    :id="field.key"
                    :name="field.key"
                    :value="form[field.key]"
                    @change="handleEditChange"
                    class="form-input"
                  >
                    <option value="" disabled>Select {{ field.label }}</option>
                    <option v-for="option in field.options" :key="option" :value="option">{{ option }}</option>
                  </select>
                  <input
                    v-else-if="field.type === 'file'"
                    type="file"
                    :id="field.key"
                    :name="field.key"
                    @change="handleFileChange"
                    class="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                  />
                </div>
                <div v-else>
                  <div class="flex items-start mb-3">
                    <span class="min-w-[120px] font-semibold text-gray-700">{{ field.label }}:</span>
                    <span class="text-gray-600 break-words ml-2">{{ displayValue(field.key, form[field.key]) }}</span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <div v-if="editing" class="pt-4 border-t border-gray-100 flex justify-end">
            <button
              type="submit"
              class="bg-green-600 text-white hover:bg-green-700 px-6 py-3 rounded-lg font-semibold shadow-md transition"
              :disabled="isSubmitting"
            >
              {{ isSubmitting ? 'Saving...' : 'Save Changes' }}
            </button>
          </div>
        </form>

        <section v-if="isStudent && enrollments && enrollments.length" class="pt-8 border-t border-gray-100">
          <h3 class="text-2xl font-bold text-gray-800 mb-4">Enrolled Courses</h3>
          <ul class="space-y-4">
            <li
              v-for="enrollment in enrollments"
              :key="enrollment.id"
              class="p-4 bg-gray-50 rounded-lg border border-gray-200 hover:shadow-lg transition duration-200 flex flex-col"
            >
              <div class="flex items-start justify-between">
                <button
                  @click="navigate(`/course/${enrollment.course.slug}`)"
                  :aria-label="`Go to ${enrollment.course.title} course details`"
                  class="text-blue-700 hover:underline font-semibold text-lg text-left"
                >
                  {{ enrollment.course.title }}
                </button>
                <span class="text-sm text-gray-500 ml-4 flex-shrink-0">
                  Enrolled: {{ formatDate(enrollment.enrolled_at) }}
                </span>
              </div>
              <div class="flex items-center justify-between mt-2">
                <span
                  class="progress-badge bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full"
                  :aria-label="`Progress: ${enrollment.progress} percent complete`"
                >
                  {{ enrollment.progress }}% Complete
                </span>
              </div>
            </li>
          </ul>
        </section>
        <section v-else-if="isStudent && enrollments && enrollments.length === 0" class="pt-8 border-t border-gray-100">
          <h3 class="text-2xl font-bold text-gray-800 mb-4">Enrolled Courses</h3>
          <li class="p-4 bg-white rounded-lg border border-gray-100 text-gray-600 text-base sm:text-lg italic text-center shadow">
            You are not enrolled in any courses yet.
          </li>
        </section>

        <div class="flex justify-center py-8">
          <button
            @click="navigate('/password_reset')"
            class="bg-yellow-500 text-white hover:bg-yellow-600 px-8 py-3 rounded-lg font-semibold text-lg shadow transition duration-200 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:ring-opacity-50"
          >
            Reset Password
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch, inject } from 'vue';

// Define complex types for clarity
interface BaseUser {
  id: number;
  username: string;
  email: string;
  role: 'student' | 'instructor' | string;
  is_active: boolean;
  date_joined: string;
  last_activity?: string;
  profile_picture?: string | File;
  first_name?: string;
  last_name?: string;
  bio?: string;
  institution?: string;
  skills?: string;
  linkedin_profile?: string;
  github_profile?: string;
  website?: string;
}

interface StudentUser extends BaseUser {
  date_of_birth?: string;
  gender?: 'male' | 'female' | 'other' | string;
  contact_number?: string;
  address?: string;
  country?: string;
  highest_qualification?: string;
}

interface Course {
  slug: string;
  title: string;
}

interface Enrollment {
  id: number;
  course: Course;
  progress: number;
  enrolled_at: string;
}

// Props
const props = defineProps<{
  user: BaseUser | null;
  enrollments: Enrollment[];
  navigate: (path: string) => void;
}>();

// Injected Context (Assuming App.vue provides this)
interface InjectedContext {
  user: BaseUser | null;
  handleLogin: (user: BaseUser) => void;
  // If navigate is also in context, you'd pull it here:
  // navigate: (path: string) => void;
}
// We will rely on props.navigate and props.user/enrollments but inject handleLogin from context
const { handleLogin, user: contextUser } = inject('user-context', {} as InjectedContext);

const BACKEND_URL = import.meta.env.VITE_APP_BACKEND_URL;

// State
const editing = ref(false);
const isSubmitting = ref(false);
const form = reactive<Record<string, any>>({});

// Determine the active user (prefer prop over injected context if both are present)
const currentUser = computed(() => props.user || contextUser.value);
const isStudent = computed(() => currentUser.value?.role === 'student');

// Initialize form state when currentUser changes
watch(currentUser, (newUser) => {
  if (newUser) {
    // Merge new user data into the reactive form object
    Object.assign(form, newUser);
  }
}, { immediate: true });

// Define editable fields based on user role
const studentFields = [
  { key: 'profile_picture', label: 'Profile Picture', type: 'file' },
  { key: 'first_name', label: 'First Name', type: 'text' },
  { key: 'last_name', label: 'Last Name', type: 'text' },
  { key: 'bio', label: 'Bio', type: 'textarea' },
  { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
  { key: 'gender', label: 'Gender', type: 'select', options: ['male', 'female', 'other'] },
  { key: 'contact_number', label: 'Contact Number', type: 'text' },
  { key: 'address', label: 'Address', type: 'textarea' },
  { key: 'country', label: 'Country', type: 'text' },
  { key: 'highest_qualification', label: 'Highest Qualification', type: 'text' },
  { key: 'institution', label: 'Institution', type: 'text' },
  { key: 'skills', label: 'Skills', type: 'text' },
  { key: 'linkedin_profile', label: 'LinkedIn', type: 'url' },
  { key: 'github_profile', label: 'GitHub', type: 'url' },
  { key: 'website', label: 'Website', type: 'url' },
];

const instructorFields = [
  { key: 'first_name', label: 'First Name', type: 'text' },
  { key: 'last_name', label: 'Last Name', type: 'text' },
  { key: 'bio', label: 'Bio', type: 'textarea' },
  { key: 'institution', label: 'Institution', type: 'text' },
  { key: 'skills', label: 'Skills', type: 'text' },
  { key: 'linkedin_profile', label: 'LinkedIn', type: 'url' },
  { key: 'github_profile', label: 'GitHub', type: 'url' },
  { key: 'website', label: 'Website', type: 'url' },
];

const editableFields = computed(() => isStudent.value ? studentFields : instructorFields);

// Event Handlers
const handleEditChange = (e: Event) => {
  const target = e.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;
  const { name, value } = target;
  form[name] = value;
};

const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    form.profile_picture = target.files[0];
  }
};

const handleEditSubmit = async () => {
  if (!currentUser.value) return;

  isSubmitting.value = true;
  
  try {
    // 1. Prepare FormData for file upload and PATCH request
    const body = new FormData();
    editableFields.value.forEach(field => {
      // Logic for profile picture file upload
      if (field.key === 'profile_picture') {
        // Only append if a new File object exists in the form state
        if (form.profile_picture instanceof File) {
          body.append('profile_picture', form.profile_picture);
        }
      } else if (form[field.key] !== undefined && form[field.key] !== null) {
        // Append all other fields
        body.append(field.key, form[field.key] === null ? '' : form[field.key]);
      }
    });

    // Get CSRF token from cookie (Preserved Django/React auth pattern)
    const csrfToken = (document.cookie.match(/csrftoken=([^;]+)/) || [])[1] || '';
    if (!csrfToken) {
      alert('CSRF token not found. Please refresh the page and try again.');
      isSubmitting.value = false;
      return;
    }

    const headers: HeadersInit = {
      'X-CSRFToken': csrfToken,
      // NOTE: Do NOT set Content-Type: 'application/json' when using FormData
    };

    // 2. Perform PATCH request
    const res = await fetch(`${BACKEND_URL}/api/users/${currentUser.value.id}/`, {
      method: 'PATCH',
      headers,
      credentials: 'include',
      body,
    });

    if (res.ok) {
      const updatedUser = await res.json();
      // Update global user state (assuming App.vue's handleLogin updates it)
      handleLogin(updatedUser);
      editing.value = false;
    } else {
      let msg = 'Failed to update profile.';
      try {
        const err = await res.json();
        // Check for common error structures
        if (err.detail) msg = err.detail;
        // Handle field-specific errors if available in the error object
        const fieldErrors = Object.values(err).flat();
        if (fieldErrors.length > 0 && typeof fieldErrors[0] === 'string') {
          msg = `Validation Error: ${fieldErrors.join('; ')}`;
        }
      } catch {}
      alert(msg);
    }
  } catch {
    alert('An unexpected error occurred while updating the profile.');
  } finally {
    isSubmitting.value = false;
  }
};

// Helper functions for display
const formatDate = (dateStr?: string) => {
  if (!dateStr) return 'N/A';
  try {
    return new Date(dateStr).toLocaleDateString();
  } catch {
    return dateStr;
  }
};

const formatDateTime = (dateStr?: string) => {
  if (!dateStr) return 'N/A';
  try {
    return new Date(dateStr).toLocaleString();
  } catch {
    return dateStr;
  }
};

const displayValue = (key: string, value: any) => {
  if (value === null || value === undefined || value === '') return 'N/A';
  
  if (key === 'date_of_birth') return formatDate(value);
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  
  if (key.includes('profile')) return value.name || 'File Selected';

  return value;
};
</script>

<style scoped>
/* Simplified input style for Vue conversion */
.form-input {
  @apply w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white text-gray-800 transition duration-150;
}
.form-label {
  @apply block text-sm font-medium text-gray-700 mb-1;
}
</style>

// frontend/shp-learners/src/pages/Profile.jsx
import React, { useContext, useState, useEffect } from 'react';
import { UserContext } from '../App.jsx';

// Use Vite env variable or fallback
const BACKEND_URL = import.meta.env.VITE_APP_BACKEND_URL;

function Profile({ user, enrollments, navigate }) {
  // Safely get context values, fallback to props or empty object
  const userContext = useContext(UserContext) || {};
  const currentUser = userContext.user || user;
  const handleLogin = userContext.handleLogin || (() => {});

  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({});

  useEffect(() => {
    if (currentUser) {
      setForm({ ...currentUser });
    }
  }, [currentUser]);

  if (!currentUser) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
        <p className="text-center text-xl text-gray-700 bg-white p-8 rounded-lg shadow-lg">
          Please log in to view your profile.
        </p>
      </div>
    );
  }

  const isUser = currentUser.role === 'student'; // Clarified 'isUser' to mean 'student'

  // Editable fields logic
  const editableFields = isUser
    ? [
        { key: 'profile_picture', label: 'Profile Picture', type: 'file' },
        { key: 'first_name', label: 'First Name', type: 'text' },
        { key: 'last_name', label: 'Last Name', type: 'text' },
        { key: 'bio', label: 'Bio', type: 'textarea' },
        { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
        { key: 'gender', label: 'Gender', type: 'select', options: ['male', 'female', 'other'] },
        { key: 'contact_number', label: 'Contact Number', type: 'text' },
        { key: 'address', label: 'Address', type: 'textarea' },
        { key: 'country', label: 'Country', type: 'text' },
        { key: 'highest_qualification', label: 'Highest Qualification', type: 'text' },
        { key: 'institution', label: 'Institution', type: 'text' },
        { key: 'skills', label: 'Skills', type: 'text' },
        { key: 'linkedin_profile', label: 'LinkedIn', type: 'url' },
        { key: 'github_profile', label: 'GitHub', type: 'url' },
        { key: 'website', label: 'Website', type: 'url' },
      ]
    : [
        { key: 'first_name', label: 'First Name', type: 'text' },
        { key: 'last_name', label: 'Last Name', type: 'text' },
        { key: 'bio', label: 'Bio', type: 'textarea' },
        { key: 'institution', label: 'Institution', type: 'text' },
        { key: 'skills', label: 'Skills', type: 'text' },
        { key: 'linkedin_profile', label: 'LinkedIn', type: 'url' },
        { key: 'github_profile', label: 'GitHub', type: 'url' },
        { key: 'website', label: 'Website', type: 'url' },
      ];

  const handleEditChange = (e) => {
    const { name, value, files } = e.target;
    if (name === 'profile_picture' && files && files[0]) {
      setForm((prev) => ({ ...prev, profile_picture: files[0] }));
    } else {
      setForm((prev) => ({ ...prev, [name]: value }));
    }
  };

  const handleEditSubmit = async (e) => {
    e.preventDefault();
    try {
      // Always use FormData for PATCH to support file uploads
      const body = new FormData();
      editableFields.forEach(field => {
        if (field.key === 'profile_picture') {
          // Only append if a new file is selected
          if (form.profile_picture instanceof File) {
            body.append('profile_picture', form.profile_picture);
          }
        } else if (form[field.key] !== undefined && form[field.key] !== null) {
          body.append(field.key, form[field.key]);
        }
      });
      // Get CSRF token from cookie
      const csrfToken = (document.cookie.match(/csrftoken=([^;]+)/) || [])[1] || '';
      if (!csrfToken) {
        alert('CSRF token not found. Please refresh the page and try again.');
        return;
      }
      // Debug: log CSRF token
      // console.log('CSRF Token:', csrfToken);

      const headers = {
        'X-CSRFToken': csrfToken,
        // Do NOT set Content-Type when using FormData
      };
      const res = await fetch(`${BACKEND_URL}/api/users/${currentUser.id}/`, {
        method: 'PATCH',
        headers,
        credentials: 'include', // This is required for cookies/session auth
        body,
      });
      if (res.ok) {
        const updated = await res.json();
        handleLogin(updated);
        setEditing(false);
      } else {
        // Try to parse error message
        let msg = 'Failed to update profile.';
        try {
          const err = await res.json();
          if (err.detail) msg = err.detail;
        } catch {}
        alert(msg);
      }
    } catch {
      alert('Failed to update profile.');
    }
  };

  // Helper to render a field if it exists
  const renderField = (label, value) => {
    // Check if value is a valid string, number, or boolean
    if (value === null || value === undefined || value === '') return null;

    // Special handling for boolean values
    if (typeof value === 'boolean') {
      value = value ? 'Yes' : 'No';
    }

    // Special handling for date_joined (assuming it's a date string)
    if (label === 'Joined' && value) {
      try {
        value = new Date(value).toLocaleDateString(); // Format date nicely
      } catch (e) {
        console.warn("Could not parse date_joined:", value);
      }
    }
    // Special handling for last_activity
    if (label === 'Last Activity' && value) {
      try {
        value = new Date(value).toLocaleString(); // Format date and time
      } catch (e) {
        console.warn("Could not parse last_activity:", value);
      }
    }
    // Special handling for Date of Birth
    if (label === 'Date of Birth' && value) {
      try {
        value = new Date(value).toLocaleDateString();
      } catch (e) {
        console.warn("Could not parse date_of_birth:", value);
      }
    }

    return (
      <div className="flex items-start mb-3">
        <span className="min-w-[120px] font-semibold text-gray-700">{label}:</span>
        <span className="ml-2 text-gray-800 break-words">{value}</span>
      </div>
    );
  };

  return (
    <section className="profile-section bg-gradient-to-br from-blue-50 to-white p-0 sm:p-0 rounded-xl shadow-2xl border border-gray-200 mx-auto max-w-full sm:max-w-2xl lg:max-w-4xl my-10">
      {/* Profile Header Card */}
      <div className="relative flex flex-col sm:flex-row items-center sm:items-end gap-6 bg-white rounded-t-xl shadow-lg px-8 py-8 border-b border-gray-100">
        <div className="relative">
          <div className="w-36 h-36 sm:w-40 sm:h-40 rounded-full border-4 border-blue-200 shadow-lg bg-gray-100 flex items-center justify-center overflow-hidden">
            {currentUser.profile_picture ? (
              <img
                src={currentUser.profile_picture}
                alt="Profile"
                className="w-full h-full object-cover rounded-full"
              />
            ) : (
              <span className="text-6xl text-blue-300 font-bold">
                {currentUser.first_name?.[0] || currentUser.username?.[0] || 'U'}
              </span>
            )}
          </div>
          {isUser && (
            <button
              onClick={() => setEditing(true)}
              className="absolute bottom-2 right-2 bg-blue-700 hover:bg-blue-800 text-white rounded-full p-2 shadow-lg transition"
              title="Edit Profile"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.38-2.827-2.828z" />
              </svg>
            </button>
          )}
        </div>
        <div className="flex-1 text-center sm:text-left">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-blue-800 mb-1">
            {isUser && `Welcome, ${currentUser.username}`}
            {currentUser.role === 'admin' && 'Admin Dashboard'}
            {currentUser.role === 'instructor' && 'Instructor Dashboard'}
          </h1>
          <div className="flex flex-wrap gap-x-6 gap-y-2 justify-center sm:justify-start mt-2">
            <span className="inline-block bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-semibold">
              {currentUser.role.charAt(0).toUpperCase() + currentUser.role.slice(1)}
            </span>
            <span className="inline-block bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-semibold">
              {currentUser.email}
            </span>
            {isUser && currentUser.is_email_verified && (
              <span className="inline-flex items-center bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm font-semibold">
                <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Email Verified
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Admin/Instructor Dashboard Link */}
      {(currentUser.role === 'admin' || currentUser.role === 'instructor') && (
        <a
          href={`${BACKEND_URL}/${'admin'}`}
          target="_blank"
          rel="noopener noreferrer"
          className="block w-full sm:w-auto mx-auto bg-green-600 text-white hover:bg-green-700 mt-4 mb-8 px-6 py-3 rounded-md font-medium text-base sm:text-lg text-center transition duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
        >
          {currentUser.role === 'admin' ? 'Go to Admin Dashboard' : 'Go to Instructor Dashboard'}
        </a>
      )}

      {/* Profile Details / Edit Form */}
      <div className="px-6 sm:px-12 py-8">
        <div className="flex flex-col md:flex-row gap-10">
          {/* Details/Form */}
          <div className="flex-1">
            <h2 className="text-2xl font-bold text-gray-800 mb-4 border-b border-gray-200 pb-2">Your Information</h2>
            {editing ? (
              <form onSubmit={handleEditSubmit} className="grid grid-cols-1 gap-6">
                {editableFields.filter(field => field.key !== 'profile_picture').map((field) => (
                  <div key={field.key} className="form-group">
                    <label htmlFor={field.key} className="block text-gray-700 font-semibold mb-1 text-sm">{field.label}</label>
                    {field.type === 'textarea' ? (
                      <textarea
                        id={field.key}
                        name={field.key}
                        value={form[field.key] || ''}
                        onChange={handleEditChange}
                        className="w-full border border-gray-300 rounded-md p-2 focus:ring-blue-500 focus:border-blue-500 text-gray-800 text-sm h-24 resize-y"
                      />
                    ) : field.type === 'select' ? (
                      <select
                        id={field.key}
                        name={field.key}
                        value={form[field.key] || ''}
                        onChange={handleEditChange}
                        className="w-full border border-gray-300 rounded-md p-2 focus:ring-blue-500 focus:border-blue-500 text-gray-800 text-sm bg-white"
                      >
                        <option value="">Select</option>
                        {field.options.map(opt => (
                          <option key={opt} value={opt}>{opt.charAt(0).toUpperCase() + opt.slice(1)}</option>
                        ))}
                      </select>
                    ) : field.type === 'file' ? (
                      <input
                        id={field.key}
                        type="file"
                        name={field.key}
                        accept="image/*"
                        onChange={handleEditChange}
                        className="w-full border border-gray-300 rounded-md p-2 text-gray-800 text-sm file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                      />
                    ) : (
                      <input
                        id={field.key}
                        type={field.type}
                        name={field.key}
                        value={form[field.key] || ''}
                        onChange={handleEditChange}
                        className="w-full border border-gray-300 rounded-md p-2 focus:ring-blue-500 focus:border-blue-500 text-gray-800 text-sm"
                      />
                    )}
                  </div>
                ))}
                {/* Profile picture input specifically for edit mode */}
                {editing && isUser && (
                  <div className="form-group">
                    <label htmlFor="profile_picture" className="block text-gray-700 font-semibold mb-1 text-sm">Profile Picture</label>
                    <input
                      id="profile_picture"
                      type="file"
                      name="profile_picture"
                      accept="image/*"
                      onChange={handleEditChange}
                      className="w-full border border-gray-300 rounded-md p-2 text-gray-800 text-sm file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                    />
                  </div>
                )}
                <div className="flex gap-3 mt-2">
                  <button
                    type="submit"
                    className="bg-green-600 text-white px-5 py-2 rounded-lg hover:bg-green-700 transition duration-200 text-sm sm:text-base font-medium flex items-center gap-1"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414L8.414 15l-3.293-3.293a1 1 0 111.414-1.414L8.414 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Save
                  </button>
                  <button
                    type="button"
                    onClick={() => { setEditing(false); setForm({ ...currentUser }); }}
                    className="bg-gray-400 text-white px-5 py-2 rounded-lg hover:bg-gray-500 transition duration-200 text-sm sm:text-base font-medium flex items-center gap-1"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                    </svg>
                    Cancel
                  </button>
                </div>
              </form>
            ) : (
              <div className="grid grid-cols-1 gap-2">
                {renderField('Username', currentUser.username)}
                {renderField('Full Name', (currentUser.first_name || currentUser.last_name) ? `${currentUser.first_name || ''} ${currentUser.last_name || ''}`.trim() : null)}
                {renderField('Bio', currentUser.bio)}
                {isUser && renderField('Date of Birth', currentUser.date_of_birth)}
                {isUser && renderField('Gender', currentUser.gender)}
                {isUser && renderField('Contact Number', currentUser.contact_number)}
                {isUser && renderField('Address', currentUser.address)}
                {isUser && renderField('Country', currentUser.country)}
                {isUser && renderField('Highest Qualification', currentUser.highest_qualification)}
                {renderField('Institution', currentUser.institution)}
                {renderField('Skills', currentUser.skills)}
                {renderField('LinkedIn', currentUser.linkedin_profile && <a href={currentUser.linkedin_profile} className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">{currentUser.linkedin_profile}</a>)}
                {renderField('GitHub', currentUser.github_profile && <a href={currentUser.github_profile} className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">{currentUser.github_profile}</a>)}
                {renderField('Website', currentUser.website && <a href={currentUser.website} className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">{currentUser.website}</a>)}
                {isUser && renderField('Email Verified', currentUser.is_email_verified)}
                {isUser && renderField('2FA Enabled', currentUser.two_factor_enabled)}
                {renderField('Joined', currentUser.date_joined)}
                {renderField('Last Activity', currentUser.last_activity)}
                {currentUser.role === 'instructor' && renderField('Instructor Rating', currentUser.instructor_rating)}
                {currentUser.role === 'instructor' && renderField('Total Reviews', currentUser.total_reviews)}
                {currentUser.role === 'instructor' && renderField('Earnings', `₹${currentUser.earnings}`)}
              </div>
            )}
          </div>
          {/* End Details/Form */}
        </div>
      </div>

      {/* Enrolled Courses Section */}
      {isUser && (
        <div className="bg-blue-50 border-t border-gray-200 px-6 sm:px-12 py-8 rounded-b-xl">
          <h2 className="text-2xl font-bold mb-4 text-blue-800">Enrolled Courses</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {enrollments && enrollments.length > 0 ? (
              enrollments.map((enrollment) => (
                <li
                  key={enrollment.course.slug}
                  className="flex flex-col justify-between p-5 bg-white rounded-lg border border-gray-100 shadow hover:shadow-lg transition-shadow duration-200"
                >
                  <div className="flex items-center gap-3 mb-2">
                    <div className="flex-shrink-0 w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center text-blue-700 font-bold text-lg">
                      {enrollment.course.title[0]}
                    </div>
                    <button
                      onClick={() => navigate(`/course/${enrollment.course.slug}`)}
                      aria-label={`View ${enrollment.course.title} course details`}
                      className="text-blue-700 hover:underline font-semibold text-lg text-left"
                    >
                      {enrollment.course.title}
                    </button>
                  </div>
                  <div className="flex items-center justify-between mt-2">
                    <span
                      className="progress-badge bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full"
                      aria-label={`Progress: ${enrollment.progress} percent complete`}
                    >
                      {enrollment.progress}% Complete
                    </span>
                  </div>
                </li>
              ))
            ) : (
              <li className="p-4 bg-white rounded-lg border border-gray-100 text-gray-600 text-base sm:text-lg italic text-center shadow">
                You are not enrolled in any courses yet.
              </li>
            )}
          </ul>
        </div>
      )}

      {/* Reset Password Button */}
      <div className="flex justify-center py-8">
        <button
          onClick={() => navigate('/password_reset')}
          className="bg-yellow-500 text-white hover:bg-yellow-600 px-8 py-3 rounded-lg font-semibold text-lg shadow transition duration-200 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:ring-opacity-50"
        >
          Reset Password
        </button>
      </div>
    </section>
  );
}

export default Profile;
